import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Rishabh Singh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex mx-10 flex-col  py-10 px-6 rounded-md mt-4 mb-6 bg-slate-100 shadow-sm dark:bg-gray-800 slg:mx-12 slg:flex-row  slg:shadow-none slg:dark:bg-transparent slg:bg-transparent">
        <div className="imgcontainer flex items-center justify-center slg:w-2/4">
          <img src={"/assets/Development-cuate.png"} className="w-full" />
        </div>
        <div className="flex flex-col justify-center slg:w-2/4">
          <div className="text-primary font-bold text-3xl my-2">
            {"<Rishabh>"}
          </div>
          <div className="font-bold text-3xl my-2 ml-5 dark:text-white">
            {"Full-Stack Developer"}
          </div>
          <div className="text-primary font-bold text-3xl my-2">
            {"</Rishabh>"}
          </div>
          <div className="font-medium text-md my-2 ml-5 dark:text-white">
            {"Developing quality software to"}
            <br />
            {"help businesses leverage their products."}
          </div>

          <div className="my-4 mx-5">
            <button className="bg-[#5672F0] text-white py-2 px-5 rounded-full focus:ring-4 focus:ring-[#C7D0FA] selection:cursor-not-allowed ">
              Read More
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
